### ISSUE TITLE
Bug: Error loading QML file in Kubuntu 20.04 LTS

### ISSUE THREAD

**Issue by NeilPandya** [Prayag2/kde_aestheticclock#2]
Hi Prayag, great work on this.

I'm using Kubuntu 20.04 LTS.

When installing, I receive the following error:
`Error loading QML file: file:///home/neil/.local/share/plasma/plasmoids/com.github.prayag2.aestheticclock/contents/ui/main.qml:5:1: module "QtQuick.Layouts" version 1.15 is not installed`

I tried to remedy the situation by installing `qml-module-qtquick-controls` and `qml-module-qtquick-layouts`.

I received the following message:
`qml-module-qtquick-controls is already at the latest version 5.12.8-0ubuntu2
qml-module-qtquick-layouts is already at the latest version 5.12.8-0ubuntu1`

Do I need to roll back to a compatible version regarding these packages or `Qt` in general?

> Operating System: Kubuntu 20.04
> KDE Plasma Version: 5.18.8
> KDE Frameworks Version: 5.68.0
> Qt Version: 5.12.8
> Kernel Version: 5.15.0-46-generic
> OS Type: 64-bit
> Processors: 16 × AMD Ryzen 9 5900HS with Radeon Graphics
> GPU: NVIDIA RTX 3080 Laptop
> Memory: 22.9 GiB of RAM

Thanks in advance,

Neil

**Comment by wplatt2** [comment]
I am having the same issue.  Kubuntu 20.04 LTS.  I found a similar issue mentioned on this [reddit post](https://www.reddit.com/r/kde/comments/jk6ey8/github_for_my_aesthetic_clock_plasmoid_open_to/).  The solution provided did not work, however.

**Comment by NeilPandya** [comment]
Closed due to inactivity. Issue was never solved.
